### ISSUE TITLE
Bad unit code for atmospheric pressure

### ISSUE THREAD

**Issue by franckLG** [easy-global-market/ngsild-api-data-models#55]
https://github.com/easy-global-market/ngsild-api-data-models/blob/79c72ff7541ab6099bcc3b43b2c3fceeb930c3e3/officeAirQuality/ngsild-payloads/openSpaceEGM-Entity.json#L204

The unit code for Pascal is PAL

Make sure that the sensor are not reporting in hectopascal (widely used unit for atmospheric pressure). In that case the unitcode would be A97

**Comment by AHABID** [comment]
I have putted it in PAL. I will keep this PR open until checking the unitCode of the device
