### ISSUE TITLE
Adding a Weather contexts file

### ISSUE THREAD

**Issue by ddumet** [easy-global-market/ngsild-api-data-models#82]
Adding a Weather contexts file, containing (obviously) all possible contexts for the weather domain.

**Comment by ddumet** [comment]
It is assumed however that its purpose is not to replace existing standard, but to add new contexts to them. Typically it is assumed context defined into standard context files like `https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld` and `https://fiware.github.io/data-models/context.jsonld` will not be duplicated and that these two context files will always be part of a "compound" context file.

Is it a good assumption ?

**Comment by bobeal** [comment]
> It is assumed however that its purpose is not to replace existing standard, but to add new contexts to them.

I guess you meant `to add new terms`?

> Typically it is assumed context defined into standard context files like `https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld` and `https://fiware.github.io/data-models/context.jsonld` will not be duplicated and that these two context files will always be part of a "compound" context file.

Core context from ETSI is always present (as per the specification). Context from Smart Data Models (your URL is an old one, isn't it?) will often be included (or at least parts we need from it).

**Comment by ddumet** [comment]
Yes probably terms, I'm struggling a bit with the vocabularies here. We're speaking of context file, so I would have assumed that it's a file that contains contexts. Adding "things" like `"cloud": "https://uri.fiware.org/ns/data-models#cloud"` is what I meant.

I don't know if `https://fiware.github.io/data-models/context.jsonld` is an old one, are they versioned ? This one is still available.

**Comment by bobeal** [comment]
> Yes probably terms, I'm struggling a bit with the vocabularies here. We're speaking of context file, so I would have assumed that it's a file that contains contexts. Adding "things" like `"cloud": "https://uri.fiware.org/ns/data-models#cloud"` is what I meant.

The context is more the whole thing. It can be seen as a business domain (weather, ...) and contains terms specific to your context / business domain.

> I don't know if `https://fiware.github.io/data-models/context.jsonld` is an old one, are they versioned ? This one is still available.

The one on fiware.github.io is still available because it is widely used. But contexts are now managed under the [Smart Data Models initiative](https://smartdatamodels.org/) and available I don't remember where (@AHABID maybe?)
