### ISSUE TITLE
Is weather context missing in agrifood context ?

### ISSUE THREAD

**Issue by ddumet** [easy-global-market/ngsild-api-data-models#86]
So we decide to create contexts for specific domain. We have now weather and agrifood contexts. Question is:

* Can we have a domain context that include another domain context, e.g. typically agrifood would include the weather context ?
* Or should we define context specific to use cases, where context file will be named after the use case, and would aggregate different "domain" contexts. E.g. for GRACED Pilze, create a context pilze.json which will contain at least agrifood and weather context files.

**Comment by bobeal** [comment]
>     * Or should we define context specific to use cases, where context file will be named after the use case, and would aggregate different "domain" contexts. E.g. for GRACED Pilze, create a context pilze.json which will contain at least agrifood and weather context files.

Yes for this one.

**Comment by ddumet** [comment]
Ok it makes sense,  I'll do that.
Additional one : one context per use case, or can we group uses cases that have the same contexts in some "generic" use cases ? E.g. it is very likely that TCA and Pilze will use the same context.

**Comment by bobeal** [comment]
> Ok it makes sense, I'll do that. Additional one : one context per use case, or can we group uses cases that have the same contexts in some "generic" use cases ? E.g. it is very likely that TCA and Pilze will use the same context.

Yes, you can group, no need to replicate the contexts. You could even go for one context for the whole project if there are not too many differences between the use cases.

**Comment by ddumet** [comment]
ok, the thing then would be to be clever in naming the context file !
Do we want names such as "graced-tca-pilze.json" ?

**Comment by bobeal** [comment]
> ok, the thing then would be to be clever in naming the context file ! Do we want names such as "graced-tca-pilze.json" ?

why not just graced.jsonld?

**Comment by ddumet** [comment]
Well, because there are other use cases that would require other contexts, e.g. SLF would need water treatment context, and PADV would likely need additional contexts, still in agriculture domain, but with additional terms related to agriculture practice.

Are you then suggesting to create a graced contexts, that include more domain contexts ?
I'm fine with that.

I guess anyway that we can start with a first version of a graced context file with, e.g. weather and agrifood first, and it doesn't harm to updated the graced context later with e.g. water-treatment, correct ?

**Comment by bobeal** [comment]
> Are you then suggesting to create a graced contexts, that include more domain contexts ? I'm fine with that.

Yes, I think this is acceptable, it won't be huge at the end and use cases don't address totally different business domains.

> I guess anyway that we can start with a first version of a graced context file with, e.g. weather and agrifood first, and it doesn't harm to updated the graced context later with e.g. water-treatment, correct ?

Indeed.

**Comment by ddumet** [comment]
ok.
Closing this now and will open a new one to create a graced context.
